### ISSUE TITLE
Occasional test failure

### ISSUE THREAD

**Issue by werebus** [umts/screaming-dinosaur#129]
There's a system test that has failed on the first try for the last few PRs. Re-running the Travis build fixes it but it seems like the tooltip doesn't always show:

https://github.com/umts/screaming-dinosaur/blob/d5d1ad9b0f292a082455ea302bf52992f4f5197d/spec/system/assignment/index_spec.rb#L14-L18

**Comment by jforgue** [comment]
Closed by #147
