### ISSUE TITLE
Don't destroy an `Assignment` when part of it is taken by another user

### ISSUE THREAD

**Issue by bandogora** [umts/screaming-dinosaur#237]
i.e. if User1 is on-call from 11/11 to 11/17 and User2 takes on-call from 11/11 to 11/15, modify the original `Assignment` so User1 is on-call from 11/16 to 11/17.

Currently the original `Assignment` would be destroyed leaving no one on-call from 11/16 to 11/17.

**Comment by sherson** [comment]
We decided not to do this and instead rely on #219.
