### ISSUE TITLE
Destroying a user leaves assignments wilth `nil` users

### ISSUE THREAD

**Issue by werebus** [umts/screaming-dinosaur#28]
@sherson  destroyed @phantompatrol in the on-call app, and now you can't look at any months where he was ever on-call.

```
ActionView::Template::Error (undefined method `last_name' for nil:NilClass):
    13:             = day.strftime '%-m/%-d'
    14:           .assignment
    15:             - if assignment.present?
    16:               = link_to assignment.user.last_name,
    17:                 edit_assignment_url(assignment)
    18:               .arrows
    19:                 - if day == assignment.start_date
```

Two possible fixes:
1.  Add a way to "deactivate" users so we can still look back and see when they once were on-call
2.  Dependent-destroy their assignments, because we really only care about the future.  :rocket:

Option two has the nice side effect that if you destroy a user and they were due to be on-call next month, then that week will suddenly be un-covered, which is kinda the truth.

**Comment by werebus** [comment]
I ended up doing option 2, in fact, for this case since @phantompatrol is already gone and there's no getting him back :sob:

**Comment by sherson** [comment]
The last time I destroyed @phantompatrol that badly was in Quake3 :godmode: 

<sub><sup>(OK OK, not really... he was pretty good)</sup></sub>

**Comment by dfaulken** [comment]
In the interest of keeping the app generic, I think I favor option 1 - not so much for the sake of looking to see when a specific person was on call, but rather for the sake of looking to see who was on call at a specific date, and not having that information be gone.

All this to say I'd advocate for dependent restrict.

**Comment by werebus** [comment]
This was done in #43, (and #105)
