### ISSUE TITLE
"Add user from another roster" select should be alphabetized

### ISSUE THREAD

**Issue by werebus** [umts/screaming-dinosaur#294]
https://github.com/umts/screaming-dinosaur/blob/334b3ba1630eb0fe283f3f26b66d94c9271b433a/app/controllers/users_controller.rb#L17

**Comment by dfaulken** [comment]
[whoops](https://github.com/umts/screaming-dinosaur/commit/8432ec04b5353c598e7dfcf061ca4c19fc603211#diff-cfdccd0a9d5df5a43aaad2a35d36ebbe187c52ad5fdc9846fa189d04537adb6eR25)
