### ISSUE TITLE
Admin CSV

### ISSUE THREAD

**Issue by sherson** [umts/screaming-dinosaur#299]
We discussed possibly having a dashboard for admins, though a CSV summary for a given roster might be more useful (can be easily Excelified for various purposes). These fields come to mind:

```
rosters.name
users.first_name
users.last_name
users.id (edit: replace this with users.email)
assignments.start_date
assignments.end_date
assignments.created_at
assignments.updated_at
```

**Comment by benmelz** [comment]
> rosters.name

I'm thinking that it makes the most sense to offer this CSV in the scope of the roster (due to admin status being on a per-roster basis). As such this column is just gonna be uniformly the same value - might make more sense to just put the roster name in the file name?

> users.id

Would this have a use case? (in the vein of don't hand out database ids for stuff)

**Comment by sherson** [comment]
So initially I drafted this issue as exactly that: just put the roster name in the file name.

However, the admin for the operations rosters may want to combine the AM and EVE rosters for whatever Excelery needs to be done, so it would probably be useful as a field.

**Comment by sherson** [comment]
Just realized I forgot to answer your second question: `users.id` might be convenient for grouping/summing per user (there are ways to do it with two columns, but having a single unique column for each user is simpler).

**Comment by sherson** [comment]
Considered suggesting spire, but I try not to use that unless necessary (it's sort-of-semi-sensitive). Could go with email instead if you'd rather avoid `users.id`.

**Comment by sherson** [comment]
Now that I think about it, email might actually be useful for other things too, so let's use that instead.
