### ISSUE TITLE
Navbar should include calendar link

### ISSUE THREAD

**Issue by dfaulken** [umts/screaming-dinosaur#32]
From https://github.com/umts/transit-it/issues/677.

**Comment by dfaulken** [comment]
Update: there isn't a navbar. Taking care of this issue will involve adding one.

I may take care of this with https://github.com/umts/screaming-dinosaur/issues/38.

**Comment by werebus** [comment]
Well, there's [this](https://github.com/umts/screaming-dinosaur/blob/master/app/views/layouts/application.haml#L10-L18)

**Comment by dfaulken** [comment]
No, I know. I meant something more like [this](https://github.com/umts/umasstransit.rodeo/blob/master/app/views/layouts/_navbar.haml).

**Comment by dfaulken** [comment]
It looks pretty navbar-y now, and does always have links to calendar(s).
