### ISSUE TITLE
Configurable reminder email for upcoming assignments

### ISSUE THREAD

**Issue by dfaulken** [umts/screaming-dinosaur#34]
From https://github.com/umts/transit-it/issues/677.

**Comment by dfaulken** [comment]
So what about these emails do we think should be configurable?

+ Whether you get them at all?
+ How far in advance?
+ Which rotations you do and do not get them for? (This will require #45.)

**Comment by dfaulken** [comment]
@sherson

**Comment by sherson** [comment]
My opinion:

* Configurable (default yes)
* Either way (I think getting a reminder the day before is fine, but some might want it configurable)
* Nah (I think if someone wants a reminder, they'll want it for all rotations)
