### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by dfaulken** [umts/screaming-dinosaur#35]
@sherson says in https://github.com/umts/transit-it/issues/677:

We might want to have admin and non-admin users (such that non-admin users can't change something they're not involved with). In theory, non-admin users need to be able to:

+ give their own assignment to another person
+ take an assignment from another person
+ take an assignment on dates that are open
+ edit an assignment's dates to allow for splitting up the assignment

**Comment by dfaulken** [comment]
Do we think we should have one admin or multiple admins per rotation?

**Comment by dfaulken** [comment]
Also, should users who are admins in one rotation not be admins in other rotations?

**Comment by sherson** [comment]
> Do we think we should have one admin or multiple admins per roster?

Having multiple could be handy.

> Also, should users who are admins in one roster not be admins in other roster?

Users who are admins in one roster may or may not be admins in another roster.

**Comment by sherson** [comment]
Hey @Anbranin, @dfaulken pointed out that it probably makes sense to create a swap system for this.

**Comment by Anbranin** [comment]
brainstorming
