### ISSUE TITLE
Request a VM

### ISSUE THREAD

**Issue by dfaulken** [umts/screaming-dinosaur#4]

**Comment by dfaulken** [comment]
@sherson pointed out that we could also just use transit-app3 for this purpose.

**Comment by sherson** [comment]
... until we know if the longterm plan is Azure or UMIT (or perhaps AWS).

**Comment by werebus** [comment]
Waiting on database.  Nearly everything else is set up.

**Comment by sherson** [comment]
Jamie is setting up the DB. He'll call us Monday with the credentials.
