### ISSUE TITLE
Friendly ID

### ISSUE THREAD

**Issue by dfaulken** [umts/screaming-dinosaur#41]
Hu-mans are too weak to consume numbers... just as they are too weak to consume gagh.

**Comment by werebus** [comment]
He was referring to using the gem, [FriendlyId](https://github.com/norman/friendly_id), for URL-slugging. Which would turn, e.g. https://umts-oncall.admin.umass.edu/rosters/1/assignments into something like https://umts-oncall.admin.umass.edu/rosters/umts-it/assignments

We use that gem on jobapps and ft-forms.
