### ISSUE TITLE
No mobile viewport directive

### ISSUE THREAD

**Issue by benmelz** [umts/screaming-dinosaur#421]
When double checking the issue fixed by #420 I also noticed that we're missing a `<meta name="viewport" content="width=device-width, initial-scale=1" />` definition in our layout (thus rendering what's basically a super zoomed out version of the desktop site while on mobile).

Posing initially as a question only because the main thing we have on the homepage is a fullcalendar, which imo actually looks a little worse when scaled up without any tinkering (at least going off the umasstransit.org homepage).

**Comment by werebus** [comment]
Looks better to me:

![Screen Shot 2024-12-03 at 16 37 45](https://github.com/user-attachments/assets/de79eb8d-513d-4b3a-9ed2-ceb87e009672)

(Screenshot is on Firefox simulating a 450px-wide screen)

At `xs` and `sm` breakpoints, the calendar ends up with an inner scroll — which you can see in the screenshot — but I think that's an acceptable trade-off for events that are big enough to actually tap on.

**Comment by benmelz** [comment]
Yeah that looks much better than the umasstransit calendar (I'm guessing the multi-view and density of events is a factor here)
