### ISSUE TITLE
Should anyone be able to destroy any assignment?

### ISSUE THREAD

**Issue by dfaulken** [umts/screaming-dinosaur#65]
In a certain sense, being on call is equivalent to money. Should anyone be able to get rid of anyone else's potential future money?

Our current system is built around the idea of accepting responsibility, but it's worth noting this also.

**Comment by jforgue** [comment]
Considering you can't edit someone else's assignment unless you're an admin. It would make sense that you also can't delete someone else's assignment unless you're an admin.

**Comment by sherson** [comment]
Currently it appears that you can _not_:

- give away your assignments
- make overlapping assignments

While you can:

- take assignments that belong to others
- create your own assignments
- edit dates of your own assignments
- delete assignments that belong to anyone

We discussed this a bit in IT today and consensus was that's all fine except that you shouldn't be able to delete any assignment (including your own) unless you're an admin.
