### ISSUE TITLE
Nav bar

### ISSUE THREAD

**Issue by mboneil10** [umts/screaming-dinosaur#68]
The nav bar doesn't look like a nav bar. Some fixes could possibly include:
- convert links to buttons
- reorder page links
- take up one line instead of three
- bootstrap

**Comment by dfaulken** [comment]
Bootstrap, in particular, is the way to go here.

@Anbranin I suggested that a good project for @mboneil10 might be working with Bootstrap.

**Comment by jforgue** [comment]
Closed with PR #91
