### ISSUE TITLE
Navigate several months into the future

### ISSUE THREAD

**Issue by mboneil10** [umts/screaming-dinosaur#70]
In order to go to September 2017, I have to click through every month in the calendar. A solution would be to add a calendar field that jumps to a selected month and year.

**Comment by dfaulken** [comment]
Sure, or even a dropdown of months, to start with.

**Comment by werebus** [comment]
With #158, clicking forward 12 months only takes me 2 or 3 seconds. Practically speaking it's also rare for an on-call rotation to be generated for more that 4 months at a time or so.
