### ISSUE TITLE
Normal user can edit their rosters

### ISSUE THREAD

**Issue by mboneil10** [umts/screaming-dinosaur#74]
A normal user is able to edit which rosters they are in. Not sure if this is intentional.

**Comment by dfaulken** [comment]
@Anbranin and I discussed this one for a while, actually. In the context of this app, it's unlikely to occur out of confusion, and if done intentionally will have relatively little practical consequences.

In particular, literally everything is paper trailed.

**Comment by dfaulken** [comment]
@Anbranin unless you have any second thoughts to offer I think we can close this.
