### ISSUE TITLE
Create a "swap" system for on-call portions

### ISSUE THREAD

**Issue by Anbranin** [umts/screaming-dinosaur#78]
I'm not sure what this would look like yet, but perhaps it would be nice to have a way for people to indicate that they want someone to take their on-call days, like by making something a different color like with bus shifts.

**Comment by dfaulken** [comment]
Sure — or maybe even an entirely different interface (like the current round-three work swap).

**Comment by Anbranin** [comment]
Mmm except I wonder if there's a way to work into it the current reality that more often it's a trade going on. Like, you could put something on-offer and request something in return and accept or reject offers.

**Comment by dfaulken** [comment]
Right, sorry, I didn't mean it should be like work swap, I meant that maybe it should be an entirely different interface, like in the way work swap is an entirely different interface.

**Comment by Anbranin** [comment]
I know

**Comment by sherson** [comment]
Because there aren't that many people on-call, we decided not to do this. Staff can coordinate via email, text, Teams, etc.
