### ISSUE TITLE
Creating new user raises exception

### ISSUE THREAD

**Issue by jforgue** [umts/screaming-dinosaur#92]
user_params:
`<ActionController::Parameters {"first_name"=>"", "last_name"=>"", "spire"=>"", "email"=>"", "phone"=>"", "reminders_enabled"=>"1", "change_notifications_enabled"=>"1", "rosters"=>["", "2"], "membership"=><ActionController::Parameters {"admin"=>"0"} permitted: true>} permitted: true>`

Exception:
Roster(#70242086014780) expected, got "" which is an instance of String(#70242013708040)

**Comment by werebus** [comment]
Some stack trace would be useful.

**Comment by dfaulken** [comment]
It's the roster membership `["", "2"]`. That needs to be interpolated in the controller into an array of actual roster objects. Not that I know what roster has a blank ID.

**Comment by jforgue** [comment]
Here's the stack trace
`ActiveRecord::AssociationTypeMismatch - Roster(#70242086014780) expected, got "" which is an instance of String(#70242013708040):
  activerecord (5.1.1) lib/active_record/associations/association.rb:239:in `raise_on_type_mismatch!'
  activerecord (5.1.1) lib/active_record/associations/collection_association.rb:240:in `block in replace'
  activerecord (5.1.1) lib/active_record/associations/collection_association.rb:240:in `replace'
  activerecord (5.1.1) lib/active_record/associations/collection_association.rb:38:in `writer'
  activerecord (5.1.1) lib/active_record/associations/builder/association.rb:119:in `rosters='`

**Comment by mboneil10** [comment]
@dfaulken, this is happening when assigning one `roster` (either Transit IT or Transit Operations) to a user. I might be wrong, but there isn't a roster with a blank ID in the database. ?

**Comment by dfaulken** [comment]
Correct, I think that's what I said. We may be misunderstanding one another.

**Comment by mboneil10** [comment]
Closed via #93
