### ISSUE TITLE
Saving an edited assignment deletes instead

### ISSUE THREAD

**Issue by jforgue** [umts/screaming-dinosaur#97]
If you save after editing an assignment, even if there is no change in dates, the assignment will be deleted.

**Comment by werebus** [comment]
😲

**Comment by jforgue** [comment]
I don't know where this is coming from.
`<input type="submit" name="commit" value="Save" class="btn btn-primary" data-disable-with="Save">`

**Comment by werebus** [comment]
https://github.com/umts/screaming-dinosaur/blob/bc471e79ce9a9d68621986a79f4eddf13d1ae7d1/app/views/assignments/edit.haml#L20-L22

Shouldn't be inside the `form_for`

**Comment by dfaulken** [comment]
Whoops
